apiVersion: v1
kind: Service
metadata:
  name: cfc-service
spec:
  selector: 
    app: cfc
  type: NodePort  
  ports:
    - port: 22
      targetPort: 22
      nodePort: 32022
  externalIPs:
    - 10.71.50.224

